### ISSUE TITLE
basic NetWork training

### ISSUE THREAD

**Issue by PatrickStarMS** [ductuantruong/enskd#4]
hello,I wonder if you've trained the base model，such cam++.
The results of my training of cam++ are not a replica of the results of your paper

**Comment by ductuantruong** [comment]
May I ask whether you used the same configuration file and Python environment provided in the README?

**Comment by PatrickStarMS** [comment]
yes，I can reproduce the results of DKD, but I cannot reproduce the Base model

**Comment by ductuantruong** [comment]
If you refer to 'Base' models as the student models trained with classification loss only, their results are from their original papers or reported in the Wespeaker toolkit; I didn't train and evaluate them from scratch.

If you find this repo helpful, please help me give it a star!

**Comment by ductuantruong** [comment]
If there is no other problems, I am closing this issue. Thank you for your interest in my work!
